export default {
    status: null,
    error: null,
    type: null,
    country: [],
    state: [],
    city: [],
    locationhub: [],
    location_portfolio: [],
    location_portfolio_links: [],
    rateAndTermLabel: [],
    portfolioPhotos: [],
    address: {},
    location_profile: {},
    vitalDetails: {},
    rateAndTerm: null,
    locationProfilePhoto: null,
    locationBasicDetails: null,
    profileAddress: null,
    locationProfileCost: {},
};
